disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- type_name
- function_body_length
- weak_delegate
- large_tuple
- todo
- inert_defer
- reduce_boolean
- syntactic_sugar
- colon
- switch_case_alignment

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

file_length:
- 300 # warning
- 301 # error

type_body_length:
- 100 # warning
- 101 # error

line_length:
- 229 # warning
- 230 # error

cyclomatic_complexity:
- 8 # warning
- 9 # error
